### ISSUE TITLE
zombie game

### ISSUE THREAD

**Issue by slowy07** [bellshade/cppSourceCode#23]
2d base game, maybe need more time 😆 @khairanabila ,how about u @ctrlbzul5 ?

**Comment by khairanabila** [comment]
> 2d base game, maybe need more time laughing @khairanabila ,how about u @ctrlbzul5 ?

okay, i in :blush:

**Comment by ctrlbzul5** [comment]
i'll check this later sensei 😅

**Comment by slowy07** [comment]
> > 2d base game, maybe need more time laughing @khairanabila ,how about u @ctrlbzul5 ?
> 
> okay, im in

okay i create algorithm and some basic logic, later i send on email

**Comment by khairanabila** [comment]
> > > 2d base game, maybe need more time laughing @khairanabila ,how about u @ctrlbzul5 ?
> > 
> > 
> > okay, im in
> 
> okay i create algorithm and some basic logic, later i send on email

okay, i search on google for sound and some stuff for better experience :blush:

**Comment by slowy07** [comment]
> i'll check this later sensei

jo jo :v mamoawkaokwoakwoakows :V

**Comment by slowy07** [comment]
@khairanabila , some texture i added on [data](https://github.com/bellshade/cppSourceCode/tree/main/sfml/zombieV/data)

**Comment by khairanabila** [comment]
> @khairanabila , some texture i added on [data](https://github.com/bellshade/cppSourceCode/tree/main/sfml/zombieV/data)

okay @slowy07 :blush:

**Comment by ctrlbzul5** [comment]
> > i'll check this later sensei
> 
> jo jo :v mamoawkaokwoakwoakows :V

aowekawek yoo fy i don't even know what should i do :V

**Comment by slowy07** [comment]
send on my email when u get 
- blood for zombie when get shooting
- shell bullet
- smoke
- fire
- bullet fire i think
- zombie
- player

wee need the sprites for walking, firing idle, moving

**Comment by khairanabila** [comment]
> send on my email when u get
> 
>     * blood for zombie when get shooting
> 
>     * shell bullet
> 
>     * smoke
> 
>     * fire
> 
>     * bullet fire i think
> 
>     * zombie
> 
>     * player
> 
> 
> wee need the sprites for walking, firing idle, moving

i have idea for player @slowy07

**Comment by khairanabila** [comment]
> > > i'll check this later sensei
> > 
> > 
> > jo jo :v mamoawkaokwoakwoakows :V
> 
> aowekawek yoo fy i don't even know what should i do :V

hahaha no prblm, u can evaluate the code :blush:

**Comment by slowy07** [comment]
> > > > i'll check this later sensei
> > > 
> > > 
> > > jo jo :v mamoawkaokwoakwoakows :V
> > 
> > 
> > aowekawek yoo fy i don't even know what should i do :V
> 
> hahaha no prblm, u can evaluate the code

okay **let's start the project** 👍🏻

**Comment by slowy07** [comment]
@ctrlbzul5 make comment, fixed indent our code for make better for user who change our code 😊

**Comment by slowy07** [comment]
@khairanabila , now u can check for algorithm and logic for our games, and tester u go on

**Comment by khairanabila** [comment]
simple shadow sprite can u commit or merge @slowy07 , @ctrlbzul5 ??
![shadow](https://user-images.githubusercontent.com/75076265/103895863-a3475b80-5123-11eb-9423-f29a8fcb7c6b.png)

**Comment by slowy07** [comment]
> simple shadow sprite can u commit or merge @slowy07 , @ctrlbzul5 ??
> ![shadow](https://user-images.githubusercontent.com/75076265/103895863-a3475b80-5123-11eb-9423-f29a8fcb7c6b.png)

ok great, @ctrlbzul5 , can u commit on [zombieV/data](https://github.com/bellshade/cppSourceCode/tree/main/sfml/zombieV/data) ??

**Comment by khairanabila** [comment]
it's to big for fire shoot or not ? @slowy07

**Comment by slowy07** [comment]
we can resize it @khairanabila

**Comment by ctrlbzul5** [comment]
> > simple shadow sprite can u commit or merge @slowy07 , @ctrlbzul5 ??
> > ![shadow](https://user-images.githubusercontent.com/75076265/103895863-a3475b80-5123-11eb-9423-f29a8fcb7c6b.png)
> 
> ok great, @ctrlbzul5 , can u commit on [zombieV/data](https://github.com/bellshade/cppSourceCode/tree/main/sfml/zombieV/data) ??

sorry for late reply. i am on it

**Comment by khairanabila** [comment]
who commit the image @slowy07 @ctrlbzul5 ?

**Comment by ctrlbzul5** [comment]
> who commit the image @slowy07 @ctrlbzul5 ?
> how ?

me.
it goes well.

**Comment by slowy07** [comment]
okay fine, tommorow we start coding, how @khairanabila ?

**Comment by khairanabila** [comment]
okay, i start tonight @slowy07 :laughing: , wher's pltfrom we use ??

**Comment by ctrlbzul5** [comment]
> okay, i start tonight @slowy07  , wher's pltfrom we use ??

arfy said windows

**Comment by khairanabila** [comment]
anyone problem while opening [sfml handling??](https://www.sfml-dev.org/tutorials/2.5/system-time.php)

**Comment by slowy07** [comment]
@khairanabila , can u build the game ?, and test it ?

**Comment by khairanabila** [comment]
> @khairanabila , can u build the game ?, and test it ?

okay @slowy07 :blush:

**Comment by khairanabila** [comment]
everything works, blood, shooting and moving hunter and zombie works
![illustration](https://user-images.githubusercontent.com/75076265/104717658-399b0300-575c-11eb-981a-6f92db739c21.png)

**Comment by slowy07** [comment]
LGTM!

> everything works, blood, shooting and moving hunter and zombie works
> ![illustration](https://user-images.githubusercontent.com/75076265/104717658-399b0300-575c-11eb-981a-6f92db739c21.png)

LGTM !, great, let's finishing this project 💻

**Comment by slowy07** [comment]
@ctrlbzul5 , can u upload this image into [zombiev/image](https://github.com/bellshade/cppSourceCode/tree/main/sfml/zombieV/src), if don't have, create one, okay 👍🏻

**Comment by ctrlbzul5** [comment]
> @ctrlbzul5 , can u upload this image into [zombiev/image](https://github.com/bellshade/cppSourceCode/tree/main/sfml/zombieV), if don't have, create one, okay 👍🏻

oky

**Comment by ctrlbzul5** [comment]
> > @ctrlbzul5 , can u upload this image into [zombiev/image](https://github.com/bellshade/cppSourceCode/tree/main/sfml/zombieV), if don't have, create one, okay 👍🏻
> 
> oky

done

**Comment by slowy07** [comment]
## close project
ok thank u for all who contributing !  👍🏻
